version: '2'

services:
  python:
    image: mypython:ubuntu  
  #  build:
  #    context: .
  #    dockerfile: Dockerfile_ubuntu
    ports:
      - 9999:8888
    volumes:
        - ../notebooks:/usr/src/notebooks
